//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalCapstone
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamScore
    {
        public int examscore_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> grade { get; set; }
        public Nullable<int> examtype_id { get; set; }
        public Nullable<int> class_id { get; set; }
        public Nullable<int> user_login { get; set; }
        public Nullable<System.DateTime> user_date { get; set; }
    
        public virtual ExamType ExamType { get; set; }
        public virtual User User { get; set; }
    }
}
