//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalCapstone
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamList
    {
        public int examlist_id { get; set; }
        public Nullable<int> class_id { get; set; }
        public Nullable<int> examtype_id { get; set; }
        public Nullable<bool> @lock { get; set; }
        public Nullable<int> user_login { get; set; }
        public Nullable<System.DateTime> user_date { get; set; }
        public Nullable<int> perfect_score { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual ExamType ExamType { get; set; }
    }
}
