//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalCapstone
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Classes = new HashSet<Class>();
            this.ClassLists = new HashSet<ClassList>();
            this.ExamScores = new HashSet<ExamScore>();
        }
    
        public int user_id { get; set; }
        public string f_name { get; set; }
        public string l_name { get; set; }
        public Nullable<long> idnumber { get; set; }
        public Nullable<long> password { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<int> program_id { get; set; }
        public Nullable<int> batch_id { get; set; }
    
        public virtual Batch Batch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class> Classes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassList> ClassLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamScore> ExamScores { get; set; }
        public virtual Program Program { get; set; }
        public virtual Role Role { get; set; }
    }
}
